# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8256f6cfc82f309562f70dcf5afe4f6f578b5211cf5a067b056380d4b7013e8f3ea635610fbda6529f2c75e468684b65c1b4a57852de88e1a12f07b2caac9a9b

test:
  secret_key_base: c84b2d1e055bc9c44a0d958bfd557e4a2f970286bd56b6af6b527e9235b1863dc0b955cd2577e62c59272fa2b5f4ce4129e6e049cd3c48ea1cdbf8ae6806247d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
